{
 "title": "Momo Store Business",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "momo_type",
    "label": "momo_type",
    "query": {
     "query": "label_values(dumplings_listing_count,type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Всего заказов",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(dumplings_listing_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Курзе ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dumplings_listing_count{id=\"12\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Кундюмы",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dumplings_listing_count{id=\"11\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sausages Trends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(dumplings_listing_count{type=\"$momo_type\"}[5m]) "
    }
   ]
  },
  {
   "title": " Равиоли",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dumplings_listing_count{id=\"14\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Бораки",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dumplings_listing_count{id=\"13\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Момо",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dumplings_listing_count{id=\"8\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Дим-самы",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dumplings_listing_count{id=\"7\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Баоцзы",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dumplings_listing_count{id=\"10\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Вонтоны",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dumplings_listing_count{id=\"9\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Хинкали",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dumplings_listing_count{id=\"2\"})"
    }
   ]
  },
  {
   "title": "Манты",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dumplings_listing_count{id=\"3\"})"
    }
   ]
  },
  {
   "title": "Гедза",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dumplings_listing_count{id=\"6\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Пельмени",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dumplings_listing_count{id=\"1\"})"
    }
   ]
  },
  {
   "title": "Цзяоцзы",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dumplings_listing_count{id=\"5\"})"
    }
   ]
  },
  {
   "title": "Буузы",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dumplings_listing_count{id=\"4\"})"
    }
   ]
  }
 ]
}