---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ .Chart.Name }}
  updatePolicy:
    updateMode: {{ .Values.VerticalPodAutoscaler.updateMode }}
  resourcePolicy:
    containerPolicies:
      {{- toYaml .Values.VerticalPodAutoscaler.resourcePolicy.containerPolicies | nindent 6 }}
