backend:
  replicaCount: 2
  revisionHistoryLimit: 15
  image:
    repository: gitlab.praktikum-services.ru:5050/std-011-021/dumplings/momo-store-backend
    pullPolicy: Always
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 50% 
  imagePullSecrets: "docker-config-secret"
  service:
    type: "ClusterIP"
    port: 8081
    targetPort: 8081
  resources:
    requests:
      memory: "260Mi"
      cpu: 0.1
    limits:
      memory: "1024Mi"
      cpu: 0.5
  VerticalPodAutoscaler:
    updateMode: "Auto"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          minAllowed:
            cpu: 0m
            memory: 0Mi
          maxAllowed:
            cpu: 1
            memory: 500Mi
          controlledResources: ["cpu", "memory"]
          controlledValues: RequestsAndLimits

frontend:
  podAnnotations: {}
  replicaCount: 1
  revisionHistoryLimit: 15
  image:
    repository: gitlab.praktikum-services.ru:5050/std-011-021/dumplings/momo-store-frontend
    pullPolicy: Always
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  imagePullSecrets: "docker-config-secret"
  service:
    type: "ClusterIP"
    port: 80
    targetPort: 8080
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "200m"
  nodeSelector:
    app: frontend
  ingress:
    className: "nginx"
    host: "momostoreby.site"
    cert_id: k8s-secret