---
apiVersion: v1
kind: ConfigMap
metadata:
  name: front-conf
data:
  front.conf: |
    server {

      listen 8080;

      location / {
      root   /usr/share/nginx/html;
      index  index.html;
      try_files $uri $uri/ /index.html;
      }

      location ~ ^/(?:products|categories|orders|metrics|auth/whoami|store) {
        proxy_pass http://backend:8081;
      }
    }