apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
    app: {{ .Chart.Name }} 
    app.kubernetes.io/component: frontend-service
    app.kubernetes.io/part-of: momo-store
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Chart.Name }} 
